# Generated by Django 4.1.1 on 2022-10-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactename', models.CharField(max_length=50)),
                ('contactemail', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('contactreason', models.CharField(max_length=50)),
            ],
        ),
    ]
