# Generated by Django 4.1.1 on 2022-10-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='reason',
            new_name='contactphone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactemail',
            field=models.EmailField(max_length=50),
        ),
    ]
