# Generated by Django 4.1.1 on 2022-10-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_contactname_contact_contname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contactemail',
            new_name='Contactemail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contactphone',
            new_name='Contactphone',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contactreason',
            new_name='Contactreason',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contname',
            new_name='Contname',
        ),
    ]
