# Generated by Django 4.1.1 on 2022-10-16 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cout',
            name='address',
        ),
    ]
