# Generated by Django 4.1.1 on 2022-10-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cout_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cout',
            new_name='checkout',
        ),
    ]
