# Generated by Django 4.1.1 on 2022-10-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_checkout_cfname'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='caddress',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
