# Generated by Django 4.1.1 on 2022-10-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_ckout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ckout',
        ),
    ]
