# Generated by Django 4.1.1 on 2022-10-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_delete_ckout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkout',
        ),
    ]
